### ISSUE TITLE
As a User, I want to search through Tweets, so I can easily find the Tweets I am interested in

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#10]
**Acceptance Criteria**
- Should be to search within all tweets. Results will be shown in the timeline tab. 

**Test cases**
- [ ] TC01 Create a tweet, search for the created tweet in the Timeline
- [ ] TC02 Search tweet by a follower in the Timeline

**Tasks**
- [ ] Prepare according data
- [ ] Create Logic to search within Tweets in the Timeline
