### ISSUE TITLE
[Feature #7] As a User, I want to be able to mention a user, so the mentioned user is notified of being mentioned

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#11]
**Acceptance Criteria**
- Should be able to mention user with the '@' in front of the username of the mentioned user.
**Test cases**
- [ ] TC01Mention user with '@' in front of the username

**Tasks**
- [ ] Prepare according data
- [ ] Update NotificationService
- [ ] Add logic to mention user in Frontend
