### ISSUE TITLE
[Feature #8] As a User, I want to be able to see the trends, so I am updated with the latest trends

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#12]
**Acceptance Criteria**
- Should be able to click on trend (hashtag followed by trend name). These tweets are at most one-week-old and contain a hashtag followed by the selected trend.

**Test cases**
- [ ] TC01Click a trend 

**Tasks**
- [ ] Prepare according data
- [ ] Create logic to view tweets with according hashtag
