### ISSUE TITLE
Feature: Update role

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#14]
**Description**
As a moderator, I want to update the role of a user, so I can promote users to moderator.

**Acceptance Criteria**
- Should be able to update role of user.

**Test cases**
- [ ] TC01 Change the role of user, view the user-status of the user in the Admin-panel.

**Tasks**
- [ ] Prepare according data
- [ ] Update UserService
- [ ] Create Logic to change user roles
