### ISSUE TITLE
Feature: Ban user

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#15]
**Description**
As an Admin, I want to ban users, so I can keep the application safe from any users that go against the rules.

**Acceptance Criteria**
- Should be able to remove/ban people from the application

**Test cases**
- [ ] TC01Click ban user, and see if the banned user still exists.

**Tasks**
- [ ] Prepare according data
- [ ] Update UserService
- [ ] Update Admin Panel
