### ISSUE TITLE
Feature: Block/unblock user

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#16]
**Description**
As a User, I want to block and unblock users, so I can block users who prove themselves 'blockworthy'

**Acceptance Criteria**
- Should be able to block and unblock users.

**Test cases**
- [ ] TC01 Block a user, post a tweet on the blocked user's account and see if the user's posts show up in the timeline.
- [ ] TC02 Unblock a user, post a tweet on the blocked user's account and see if the user's posts show up in the timeline.

**Tasks**
- [ ] Prepare according data
- [ ] Update UserService
- [ ] Update TweetService
- [ ] Update Frontend
