### ISSUE TITLE
Feature: Add profile details

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#18]
**Description**
As a User, I want to add my profile details, so other users can see my details.

**Acceptance Criteria**
- Should be able to add profile details.

**Test cases**
- [ ] TC01 Add profile details

**Tasks**
- [ ] Prepare according data
- [ ] Create form to add profile details
