### ISSUE TITLE
What technical stack will there be used to build the Kwetter Application?

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#2]
**Learning goals**
- I want to know what coding languages and frameworks are most suitable to build a scalable microservice architecture.
- I want to know what Databases are most suitable to efficiently store and query data.
- What messaging broker will there be used to send and receive messages

**Tasks**
- [x] decide coding languages and frameworks
- [x] decide most suitable databases
- [x] decide on a messaging broker
