### ISSUE TITLE
As the Product owner, I want to have role based permission, so I can have multiple roles to login with

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#6]
**Acceptance Criteria**
- Should be able to log in with the Admin role

**Test cases**
- [ ] TC01Login to the application with an account with the User role
- [ ] TC02Login to the application with an account with the Admin role

**Tasks**
- [ ] Add Roles to Auth0
- [ ] Add authorization
