### ISSUE TITLE
[Feature #4] As a User, I want to be able to follow/unfollow another user, so I can view the activity of the followed users

### ISSUE THREAD

**Issue by SiemLuc** [FHICT-S-Siem/S6-SiemLucassen-Kwetter#9]
**Acceptance Criteria**
- Should be able to follow/unfollow an authenticated user

**Test cases**
- [ ] TC01 Follow an authenticated user
- [ ] TC02 Unfollow a followed user

**Tasks**
- [ ] Prepare according data
- [ ] Create FollowService
